version: "3.1"

services:

  db:
    image: postgres
    restart: always
    #expose:
    #  - 5432
    environment:
      POSTGRES_PASSWORD: password
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres




  django_server:
    build: .
    command:  python3 src/testDT/manage.py runserver 0.0.0.0:8000
    volumes:
    - .:/main
    environment:
      POSTGRES_PASSWORD: password
      PGPASSWORD: password
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      DB_HOST: db


    ports:
      - 8000:8000

    depends_on:
      - db




