# Generated by Django 3.0.7 on 2020-06-09 08:10

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Post",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=1024)),
                ("text", models.CharField(max_length=8192)),
                ("uuid", models.CharField(max_length=1024)),
                ("votes", models.IntegerField()),
                ("username", models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=256)),
                ("text", models.CharField(max_length=8192)),
                (
                    "create_date",
                    models.CharField(
                        default=datetime.datetime(2020, 6, 9, 8, 10, 15, 441238),
                        max_length=256,
                    ),
                ),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="news.Post",
                    ),
                ),
            ],
        ),
    ]
